version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: echo "127.0.0.1 too.many.sub.domains.local" >> /etc/hosts
      - run: php -S 0.0.0.0:8585 &
      - run: ./node_modules/.bin/cypress run
      - run: npm install cypress@13.1.1
      - run: ./node_nodules/.bin/cypress run
